external_components:
  - source:
      type: local
      path: components

esphome:
  name: test-cover-device

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

spi:
  clk_pin: GPIO4
  miso_pin: GPIO5
  mosi_pin: GPIO6

elero:
  cs_pin: GPIO7
  gdo0_pin: GPIO3
  freq0: 0xc0
  freq1: 0x71
  freq2: 0x21

cover:
  - platform: elero
    blind_address: 0xa831e5
    channel: 4
    remote_address: 0xf0d008
    name: Schlafzimmer
